### ISSUE TITLE
Crash on Linux in Velius boss fight

### ISSUE THREAD

**Issue by s3lph** [tizian/Cendric2#214]
Cendric2 on Linux (installed and run via Steam) sporadically crashes with a segmentation fault during the boss fight against Velius.

Coredump:
```
$ coredumpctl gdb 12582
           PID: 12582 (Cendric)
           UID: 1000 (s3lph)
           GID: 1000 (s3lph)
        Signal: 11 (SEGV)
     Timestamp: Sun 2018-09-09 21:02:33 CEST (3min 25s ago)
  Command Line: ~s3lph/.local/share/Steam/steamapps/common/Cendric/Cendric
    Executable: ~s3lph/.local/share/Steam/steamapps/common/Cendric/Cendric
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (s3lph)
       Boot ID: <~>
    Machine ID: <~>
      Hostname: <~>
       Storage: /var/lib/systemd/coredump/core.Cendric.1000.<~>.12582.1536519753000000.lz4
       Message: Process 12582 (Cendric) of user 1000 dumped core.
                
                Stack trace of thread 12582:
                #0  0x00000000007457c8 n/a (~s3lph/.local/share/Steam/steamapps/common/Cendric/Cendric)
                #1  0x00000000430e0000 n/a (n/a)

GNU gdb (GDB) 8.1.1

// ...

Core was generated by `~s3lph/.local/share/Steam/steamapps/common/Cendric/Cendric'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000007457c8 in AllyBehavior::updateAggro() ()
[Current thread is 1 (Thread 0x7f4a7a39df00 (LWP 10305))]
(gdb) bt
#0  0x00000000007457c8 in AllyBehavior::updateAggro() ()
#1  0x0000000000745417 in AllyBehavior::update(sf::Time const&) ()
#2  0x000000000073bac1 in LevelMovableGameObject::update(sf::Time const&) ()
#3  0x00000000006db3e7 in Enemy::update(sf::Time const&) ()
#4  0x0000000000712085 in VeliusVictim::update(sf::Time const&) ()
#5  0x00000000005b669d in Screen::updateObjects(GameObjectType, sf::Time const&) ()
#6  0x00000000005a42b5 in LevelScreen::execUpdate(sf::Time const&) ()
#7  0x00000000005b756d in Screen::update(sf::Time const&) ()
#8  0x00000000005a002c in ScreenManager::update(sf::Time const&) ()
#9  0x0000000000837248 in Game::run() ()
#10 0x0000000000535d9b in main ()
```

The stack trace is consistent across all coredumps i looked at.

- Cendric2 Version 1.1.1 64bit
- Linux Kernel 4.18.6

**Comment by Ironbell** [comment]
Hey @s3lph, thanks for the report! Do you remember the spells you used when the crash happened? Was there a Gargoyle active?

**Comment by s3lph** [comment]
No, there wasn't. I was actively using fire and ice, and additonally had wind, telekinesis and gravity equipped.  AFAICT the crash always happens when a fire or ice projectile hit the "real" Velius in those phases where he summoned multiple copies of himself.

**Comment by Ironbell** [comment]
Github rules automatically closed the issues, I'll have to test it though and upload the new builds.

**Comment by Ironbell** [comment]
It's uploaded both on steam and on github.

**Comment by s3lph** [comment]
Appears to be fixed, thanks a lot!
